### ISSUE TITLE
ValueError: Can't export empty scenes!

### ISSUE THREAD

**Issue by JeongMin-D** [leggedrobotics/terrain-generator#7]
Has anyone resolved this issue?
I was setting up using conda and got the error below.
- Blender 4.2.0
- Python 3.8

=====================================================================================================
Traceback (most recent call last):
  File "examples/generate_with_wfc.py", line 265, in <module>
    create_mesh_from_cfg(
  File "examples/generate_with_wfc.py", line 81, in create_mesh_from_cfg
    tiles, wave, wave_order, wave_names = solve_with_wfc(cfg, shape, initial_tile_name)
  File "examples/generate_with_wfc.py", line 35, in solve_with_wfc
    tiles = create_mesh_pattern(cfg)
  File "/home/jmin/isaac_ws/terrain-generator/terrain_generator/trimesh_tiles/mesh_parts/create_tiles.py", line 101, in create_mesh_pattern
    tiles = ray.get(tiles)
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::create_mesh_tile() (pid=42898, ip=192.168.0.240)
  File "/home/jmin/isaac_ws/terrain-generator/terrain_generator/trimesh_tiles/mesh_parts/create_tiles.py", line 79, in create_mesh_tile
    mesh = cached_mesh_gen()
  File "/home/jmin/isaac_ws/terrain-generator/terrain_generator/utils/utils.py", line 99, in mesh_gen
    mesh = mesh_gen_fn(cfg)
  File "/home/jmin/isaac_ws/terrain-generator/terrain_generator/trimesh_tiles/mesh_parts/basic_parts.py", line 184, in create_wall_mesh
    mesh = trimesh.boolean.difference([mesh, door], engine=ENGINE)
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/trimesh/boolean.py", line 25, in difference
    result = _engines[engine](meshes, operation='difference', **kwargs)
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/trimesh/interfaces/blender.py", line 52, in boolean
    with MeshScript(meshes=meshes,
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/trimesh/interfaces/generic.py", line 51, in __enter__
    mesh.export(file_obj=file_obj.name)
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/trimesh/scene/scene.py", line 837, in export
    return export.export_scene(
  File "/home/jmin/anaconda3/envs/wfc/lib/python3.8/site-packages/trimesh/exchange/export.py", line 224, in export_scene
    raise ValueError("Can't export empty scenes!")
ValueError: Can't export empty scenes!
(create_mesh_tile pid=42898) I0000 00:00:1722818762.275902   42898 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
(create_mesh_tile pid=42898) stair_0.0_0.5_wall_('up', 'right')_12 does not exist in cache, creating stair_0.0_0.5_wall_('up', 'right')_12_a16aac5f7b26f51597bd16cdfe7bf8db.obj ...
(create_mesh_tile pid=42909) stair_0.0_0.5_wall_()_13 does not exist in cache, creating stair_0.0_0.5_wall_()_13_cf1ab0246a68502c82724653409321e0.obj ...
(create_mesh_tile pid=42919) stair_0.0_0.5_wall_('middle_left', 'middle_right')_0 does not exist in cache, creating stair_0.0_0.5_wall_('middle_left', 'middle_right')_0_6749081b9b3074578e83ca480fe8f76b.obj ...
(create_mesh_tile pid=42906) I0000 00:00:1722818762.442303   42906 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
(create_mesh_tile pid=42909) I0000 00:00:1722818762.395211   42909 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
(create_mesh_tile pid=42910) stair_0.0_0.5_wall_('middle_left', 'middle_bottom')_13 does not exist in cache, creating stair_0.0_0.5_wall_('middle_left', 'middle_bottom')_13_69657f91659fa50311ce5d06bb6a889a.obj ...
(create_mesh_tile pid=42906) stair_0.0_0.5_wall_('up', 'right')_13 does not exist in cache, creating stair_0.0_0.5_wall_('up', 'right')_13_1518a4ad415d37f31374a46c22e58856.obj ...

**Comment by JeongMin-D** [comment]
It seems to be a problem with my version of blender. I solved it using the commands below.
```
sudo snap install blender --channel=3.5/stable --classic
```
